### ISSUE TITLE
nxtrim does not remove Illumina adapters

### ISSUE THREAD

**Issue by mmokrejs** [sequencing/NxTrim#34] opened 2017-04-07 22:23 UTC
Hi Jared,
  in issue #32 you asked me for some testcases. For an "easier" start I sticked to the default settings, so I let `nxtrim v0.4.1-7db257e` to flip `RF` matepair reads into `FR` orientation. Below are 8 example original reads from NextSeq device having a perfect match or just a single mismatch.

```
> NB501598:62:HFYJ5AFXX:1:11305:22286:4051 1:N:0:GCCAAT
Length=155

 Score =   127 bits (64),  Expect = 2e-28
 Identities = 64/64 (100%), Gaps = 0/64 (0%)
 Strand=Plus/Minus

Query  1   AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTG  60
           ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  79  AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTG  20

Query  61  CTTG  64
           ||||
Sbjct  19  CTTG  16


> NB501598:62:HFYJ5AFXX:1:11201:5173:2350 1:N:0:GCCAAT
Length=155

 Score =   127 bits (64),  Expect = 2e-28
 Identities = 64/64 (100%), Gaps = 0/64 (0%)
 Strand=Plus/Minus

Query  1   AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTG  60
           ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  68  AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTG  9

Query  61  CTTG  64
           ||||
Sbjct  8   CTTG  5


> NB501598:62:HFYJ5AFXX:1:21203:4547:6784 1:N:0:GCCAAT
Length=155

 Score =   125 bits (63),  Expect = 7e-28
 Identities = 63/63 (100%), Gaps = 0/63 (0%)
 Strand=Plus/Minus

Query  2    GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGC  61
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  155  GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGC  96

Query  62   TTG  64
            |||
Sbjct  95   TTG  93


> NB501598:62:HFYJ5AFXX:1:11108:9901:15649 1:N:0:GCCAAT
Length=155

 Score =   119 bits (60),  Expect = 4e-26
 Identities = 63/64 (98%), Gaps = 0/64 (0%)
 Strand=Plus/Minus

Query  1    AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTG  60
            |||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||
Sbjct  155  AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTGCTG  96

Query  61   CTTG  64
            ||||
Sbjct  95   CTTG  92


> NB501598:62:HFYJ5AFXX:1:11103:16230:15181 1:N:0:GCCAAT
Length=155

 Score =   119 bits (60),  Expect = 4e-26
 Identities = 63/64 (98%), Gaps = 0/64 (0%)
 Strand=Plus/Minus

Query  1    AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTG  60
            |||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||
Sbjct  155  AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATATCGTATGCCGTCTTCTG  96

Query  61   CTTG  64
            ||||
Sbjct  95   CTTG  92


> NB501598:62:HFYJ5AFXX:1:21102:17028:3960 1:N:0:GCCAAT
Length=155

 Score =   111 bits (56),  Expect = 1e-23
 Identities = 62/64 (97%), Gaps = 0/64 (0%)
 Strand=Plus/Minus

Query  1   AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTG  60
           ||||||||||||||||||||||||||| ||||||||||||||||||||||||||||||| 
Sbjct  85  AGATCGGAAGAGCACACGTCTGAACTCAAGTCACGCCAATATCTCGTATGCCGTCTTCTC  26

Query  61  CTTG  64
           ||||
Sbjct  25  CTTG  22


> NB501598:62:HFYJ5AFXX:1:21204:21059:2846 1:N:0:GCCAAT
Length=153

 Score =   107 bits (54),  Expect = 2e-22
 Identities = 54/54 (100%), Gaps = 0/54 (0%)
 Strand=Plus/Minus

Query  1   AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGT  54
           ||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  54  AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGT  1


> NB501598:62:HFYJ5AFXX:1:21111:16062:11848 1:N:0:GCCAAT
Length=153

 Score =   105 bits (53),  Expect = 6e-22
 Identities = 56/57 (98%), Gaps = 0/57 (0%)
 Strand=Plus/Minus

Query  1   AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTT  57
           |||||||||||||||||||||||||||||||||||||||||||||| ||||||||||
Sbjct  57  AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGAATGCCGTCTT  1
```

```
R1.fastq

@NB501598:62:HFYJ5AFXX:1:11103:16230:15181 1:N:0:GCCAAT
AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATATCGTATGCCGTCTTCTGCTTGAAAAAAAAATAGGGGGGGGGGGGGGGGGTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
A/AAAEE///EEEE/E//EAEEEEEEEEE/EAE/<//EEEEEEE//EE/6EEAEEEAE/EEAE/EEEEE6EEA/////////////<E///</A//<<///</</6////E/EE/EEE/E/A///E<//A/AAA6</A/EE/<E<<A<AEEEA/A
@NB501598:62:HFYJ5AFXX:1:11108:9901:15649 1:N:0:GCCAAT
AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTGCTGCTTGAAAAAAAAATGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
/AAAAEE/6E6EE6AEEAEEAE//EEEEEEE///E/E//EAE///AAEEE//EEEE/E/////A//E66EEE/////A/EEEAE/EAE//</EEEEEEE/EEEEAEAAAE<A<EA/<EEEAEEEEEEEEEEA<<<EA<<EE<<EEEEEEAEAEA/
@NB501598:62:HFYJ5AFXX:1:11201:5173:2350 1:N:0:GCCAAT
ATGTATTTCAATGGCTCACTATGAGCTTCCAGGAGCTAACTGAAGTCTCCATGAATCACGTGATGGCCAAGCTTTTTGGACTTCTATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTGAAAA
+
AAAAAEEEEEEEEEEEE6EEEEEEEAEEEAEEE6EEEEEEEEEEAEEEAEEEE/EEEEEEEE6EEEE<EEEEAEEEEEEAEEEEE/EEEEEEAEEAEEEEEAEEE<AEE//EEEEAEEE/EEEEEEE/<EAEEEE/EEEEEE<AEA<<AEEAAAE
@NB501598:62:HFYJ5AFXX:1:11305:22286:4051 1:N:0:GCCAAT
TTAATCATAAACAAATAAACCAACCCACATAAACCCTCGAATAATATAAACAGATAAACGTTAGAAGGATGGACCAAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGCGGG
+
AA/AAE6EEE/A//AE//6//EAEEAEEE//EE//////EA/E6///////E////E/////AAEE//EA//E<6EE/E/6//AE/E/AEAEA///AAAA<//6</AE/<<E/EE/A////A/EEAE/6/A/E6/<<//AEAEAEEE///////<
@NB501598:62:HFYJ5AFXX:1:21102:17028:3960 1:N:0:GCCAAT
CCATATGTACAGAGTTTGTACAAACTAATACAGCTCACGACAATTAAAACTACAAAATAAATACTAAGAAAGATCGGAAGAGCACACGTCTGAACTCAAGTCACGCCAATATCTCGTATGCCGTCTTCTCCTTGAAAAAAAAACGGGGGGGGCGG
+
///AAE/AE//EE/A/EEEEAE6EAEAEAEEEE/E/EE</A/EE/EEE/AEEAEEEE66EEEE6EEEEAAAEEEE/EEE6EEE6/EEE//E//A/EE/EAEE//<6EEEEAA6A</<EE/66/EE/E/E/AEAEEE//EA///////////E/</
@NB501598:62:HFYJ5AFXX:1:21111:16062:11848 1:N:0:GCCAAT
TTAACCCAGAGTTTGTCCATATTTTATACAACCATGGGGTGAAACAAGATCTTTATAACAGACAGGTTATGAGAAGGTCATCCTTCGAGATCTTTAAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGAATGCCGTCTTCT
+
A/AAAEAEAEEEEE/EEA/AAEEEAE6//EEEA/E//A<//AEE//E6EE/AEE/EEE/E/E/AA/EAA///AEE//A/A//<6E66EEE/E/AA6EAE//6/EAA///AAE<//EAEEE/E6/AA/<A<//6A</EAAE///E<</6A//AA/<
@NB501598:62:HFYJ5AFXX:1:21203:4547:6784 1:N:0:GCCAAT
GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAATGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
A/AAAEEEEEEEEEEEE/EEEAEEEA<EEEEEEEEEEAEEE/E<EEEEEAEEEEEEEEEEEE/E/EEEEEE////E/<AEEAEEEEEEEEAEEEEEEEEEEEAE/<AAEAEEEEEEEEAE<AAEAE/AE/A6A/<<AAE<//<A</AA/A<<A</
@NB501598:62:HFYJ5AFXX:1:21204:21059:2846 1:N:0:GCCAAT
GCCCTTGTCCTTTGACTCATATACCCTTCTTTATCTCTGATGGAGTTTGTGGTCAGATTATATGTGTATAAGATAAAGCTGTAGTATAGGGGTTACGCCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCT
+
AAAAAEEEEAEEEEAEEEEEEEE6EAAEEEEEEEEEE//EEEEEEEEEEE<EEE/EEAEA//EAAEE/AAE/E6E/E/AA/EAEE/<AAEEEEEE//E6EEEE//E/A/EAEE<<AEEAAAEE<A/<AAA<A<AA6<EA<<<A<<AAA<6AA/<<


R2.fastq

@NB501598:62:HFYJ5AFXX:1:11103:16230:15181 2:N:0:GCCAAT
ACAACCTAACATCTTATTTAATTCAAAGAGTTTATAAATAACTTTTCCCAATATAATTAAAAAAAAATAGTATATCCTTGCGAGTCCGTCTTGTCTCCTGTCTCTTATACACATCTAGATGTGTATAAGAGACAGGCTGTGATGATAGTATGTCG
+
A/66///////A//E///A//EE/A66/AEE/A////E/E/EAEEE//<////////////A/A/6////EE//E//EE///EEE//EE<EEAE/<AEEE/EE/6EE//E/E//E/<///<</E/<//E//A</E//E///</6/////6/A///
@NB501598:62:HFYJ5AFXX:1:11108:9901:15649 2:N:0:GCCAAT
ACAAATTAATAGCATATACAATTCAAACAGTCAATAACACGTAACTACCAGAAACAATAAAAAAAAAATCGCTTAGAGCTGTCTCTTATACACATCTAGATGTGTATAAGAGACAGGGCACGCTCGGTGTACCCGCGGGGGCGCAGCGATGCGGG
+
/AA///A/6E6AE/E/E////EEA/E//E/6E//E/E/E//EE/EE/<//A/EA//<E/66/EEA6AA6//EEEEEEEAAEEEEAEEEE/////<AE/E//E<E///A/EAA/AEE/E/</A//EAEEEE/E//E<EEEEAEEE/EAE/<<<AA<
@NB501598:62:HFYJ5AFXX:1:11201:5173:2350 2:N:0:GCCAAT
ATAGAAGTCCAAAAAGCTTGGCCATCACGTGATTCATGGAGACTTCAGTTAGCTCCTGGAAGCTCATAGTGAGCCATTGAAATACATCTGTCTCTTATACACATCTGACGCTGCCGACGAAGATGTGTATAAGAGACAGCAGGCCCAGGGAGTAA
+
AAAAAEEE/EEEEEEEEEEAEE/EEEE/EEEEEEEAEEEEEAEAE<EE/EEEEEEEEEEE6EEEEE/EEEEAE<EAEEE///AAEEEEEAEEEEEEEE/A/E<EAEAEEE/EE/AE<EE/EE/EEA/<AEAEEEAEAEEA/A<<</<AE<</</<
@NB501598:62:HFYJ5AFXX:1:11305:22286:4051 2:N:0:GCCAAT
TGGTCCATCCTTCTAACGGTGCGCTGGAGAAAGTCTTCGAGGGTTGATGTGGGTGGGTTTCCTGCTGCCTCCATACCTGTCTCTTATACACATCTGACGCTGCCGACGAAGATGTGTATAAGAGACAAGATCGGAAGAGCGTCGTGTAGGGAAAG
+
AAAAA/EAE/EEEEE6EEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEA<EEEEEE<<EE</EEEEEEEEEEEEAEEEEEAAEAE/EE///AA</EA/<E</<EE<<AEEAEE</<EA/EA<A/EE<6<</AE6A/6<AA/EE/
@NB501598:62:HFYJ5AFXX:1:21102:17028:3960 2:N:0:GCCAAT
TTCTTAGTATTTATTTTGTAGTTTTAATTGTCGTGAGCTGTATTAGTTTGTACAAACTCTGTACATATGCCTGTCTCTTATACCCATCTGCCGCTGCCGACGAAGATGTGGATAAGAGGCAGCTTCAGGATTACTAAAAACTTCTGAGACGGGTG
+
/A/A//EEE6E//EEAEE66E66AE666EEEEA/E/E/AEEEEE6E6EAAE//////E//E//////EEE<EEEEEEEEAE/</E/E/EE</E</AA<A//EE/EE/EAA/////E/E///E/A/A/<E///////E///AA//<A/A//AAE</
@NB501598:62:HFYJ5AFXX:1:21111:16062:11848 2:N:0:GCCAAT
TAAAGCTCTCGAAGGATGACCTTCGCATAAACTCTCTCTTATAAACATCTTGTTTCACAACATGGTTGGATAAAATATGGACAAACTCTGGGTTAAAGATCGGAAGAGCGTCGTGTAGGGAAAAAGTGTATATCTAGGAGGTCCCCGTATAATAA
+
6AAAAAEAE/EEEE/E//E/AE/E//EEAA/EE6EEA//EE/EEE6EE<E//EEE/E///EEE//E/E/EEEEEA/E/A/E/EEE/E6///6E<AAEEEE/EAE<EAEE//<//<EA//EE<E///A</E/<//A/////6///666/A//6///
@NB501598:62:HFYJ5AFXX:1:21203:4547:6784 2:N:0:GCCAAT
GAGGGATGTCATTACCTCTTTAATGTTTCTGTACAGAATATCATTATTTTTGTCAAGAAATAATCAAAGAATGAGGAAATCATACAGGACAGGATAAGGAAATGTTAAAGCTGTATTATGTCTGTCTCTTATACACATCTAGATGTGTATATGAG
+
AAAAAEE6EEEEAEEAEEAAEAEEEAE//E//E/EEEE/EA<EEE/A/A/</E/EA/AEA///////<///A<<AAEAEAEEEA/EEEEEEEEEEAEAEE/EEAE//A<AE/E<E/EEAAEAEAA/AEAEEE/A////6E/<A/E<A6A/A/A<6
@NB501598:62:HFYJ5AFXX:1:21204:21059:2846 2:N:0:GCCAAT
GGCGTAACCCCTAGACTACAGCTGTCTCTTATACACATCTAATCTGACCACAAACTCCATCAGAGATAAAGAAGGGTATATGAGTCAAAGGACAAGGGCAGATAGGAAGAGCGTCGTGTAGGGAAAGACTGTAGATCTCGGTGGTCGCCGTAAAA
+
AAAAAEE6/AEA/E/AEA/AEEEEEEEEEE6E6AE/EE/E/AE/EEAAAE<AAEAE/<AAAAE6A/E6E6EA/AEAEEEAEEEEA/A/AE/AE/E//EAAE/E//<EEE/EEAEE/EEEE/A<EE//E/A/<E<A</66/<//AEAAEEEEA//<
```

**Comment by jaredo** [comment] 2017-04-08 11:23
I see the confusion now. The problem is that the external adapter reads are not being removed, the Nextera junction adapter is removed though. Correct?

Nxtrim expects external adapter reads to already be removed.  This is usually done by default in the onboard sequencer software or there are other tools available eg. trimmomatic/cutadapt.

Nxtrim *will* check if the template (molecule length) was less than 2*read_length. In this case R1 can read into the external adapter on the other side (this should be rare) and will trim this out appropriately. This is the only thing it does with external adapters. 

NxTrim is designed to remove Nextera junction adapters and arrange your reads in an appropriate input for assemblers, it implements the bespoke logic required for this. It is not a comprehensive adapter manipulation tool like trimmomatic etc.

**Comment by jaredo** [comment] 2017-04-08 20:06
eg. you could clean up your reads with something like this:

```
trimadap-mt -5 AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC example/iss34.r1.fq.gz | gzip -c > 1.fq.gz
trimadap-mt -5 GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT example/iss34.r2.fq.gz | gzip -c > 2.fq.gz
```

https://github.com/lh3/trimadap

**Comment by jaredo** [comment] 2017-04-10 10:40
I am going to close this one.

**Closed by jaredo** 2017-04-10 10:40 UTC
